apiVersion: v1
kind: Service
metadata:
  name: ms-cancelamento-debito-service
spec:
  selector:
    app: cancelamento-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
