name: Build and Deploy Java App to EKS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 011706314791.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          IMAGE_REPO=011706314791.dkr.ecr.us-east-1.amazonaws.com/itau-daily-banking/ms-cancelamento-debito
          docker build -t ms-cancelamento-debito .
          docker tag ms-cancelamento-debito:latest $IMAGE_REPO:latest
          docker push $IMAGE_REPO:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name dailybanking-case

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
